### ISSUE TITLE
The gem I'm using is buggy

### ISSUE THREAD

**Issue by dyep49** [dyep49/Umpire-Auditor#1]
The gem I'm using hasn't been updated in years and is pretty buggy. It was supposed to parse a lot of the xml I'm using. It works inconsistently. I spent hours trying to fix it, but as soon as I fixed one problem, another problem would pop up. Now, I have to use Nokogiri to do it myself. I know how to do it, it's just annoying. That's all...

**Comment by MikeSofaer** [comment]
I know that feeling well. We will talk about testing API consumers at some point this week.
