### ISSUE TITLE
Working with a big database

### ISSUE THREAD

**Issue by dyep49** [dyep49/Umpire-Auditor#2]
I have to seed and work with a big database (about a million rows). Unsurprisingly, the seed task is incredibly slow. A rough estimate puts the seed time at about 3 hours. I need to figure out how to refactor the code to increase efficiency. I'm exploring different options now, but I would certainly be open to any advice.

**Comment by MikeSofaer** [comment]
Don't use ActiveRecord, look at ways to load postgres tables from files.

**Comment by amadden80** [comment]
Another issue you will run into is that heroku limits the number of table rows you can use for free.
If you do not want to pay $, develop with less than 10,000 rows.

**Comment by dyep49** [comment]
Yeah, I just accepted I'd have to pay the $9/month
